apiVersion: v1
kind: Service
metadata:
  name: web-to-nginx
spec:
  type: LoadBalancer
  selector:
    app: web-to-nginx
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-to-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-to-nginx
  template:
    metadata:
      labels:
        app: web-to-nginx
    spec:
      containers:
        - name: web-to-nginx
          image: mmokijewski/web-to-nginx:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
